# docker-compose configuration file for django-class-based-views-tutorial

web:
  build: .
  command: "gunicorn -c curd/settings/gunicorn.py --reload curd.wsgi:application"
  ports:
    - "8000:8000"
  volumes:
    - .:/usr/src/app
  links:
    - postgres
  environment:
    - DJANGO_SETTINGS_MODULE=curd.settings.local

postgres:
  image: postgres:9.4
